// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Resty.Data;

#nullable disable

namespace Resty.Data.Migrations
{
    [DbContext(typeof(RestyDbContext))]
    [Migration("20221025081153_Updated models 4")]
    partial class Updatedmodels4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("Blogs_Seq", "public")
                .StartsAt(7L);

            modelBuilder.HasSequence<int>("BlogUserBookmark_Seq", "public")
                .StartsAt(4L);

            modelBuilder.HasSequence<int>("BlogUserComment_Seq", "public")
                .StartsAt(3L);

            modelBuilder.HasSequence<int>("BlogUserReview_Seq", "public")
                .StartsAt(7L);

            modelBuilder.HasSequence<int>("Tags_Seq", "public")
                .StartsAt(9L);

            modelBuilder.HasSequence<int>("Users_Seq", "public")
                .StartsAt(4L);

            modelBuilder.Entity("BlogTag", b =>
                {
                    b.Property<int>("BlogsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("BlogsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BlogTags", (string)null);

                    b.HasData(
                        new
                        {
                            BlogsId = 1,
                            TagsId = 1
                        },
                        new
                        {
                            BlogsId = 2,
                            TagsId = 2
                        },
                        new
                        {
                            BlogsId = 2,
                            TagsId = 3
                        },
                        new
                        {
                            BlogsId = 3,
                            TagsId = 4
                        },
                        new
                        {
                            BlogsId = 4,
                            TagsId = 5
                        },
                        new
                        {
                            BlogsId = 5,
                            TagsId = 6
                        },
                        new
                        {
                            BlogsId = 6,
                            TagsId = 7
                        },
                        new
                        {
                            BlogsId = 6,
                            TagsId = 8
                        });
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"Blogs_Seq\"')");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Preview")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedDateUtc");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "TEST",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 8, 11, 52, 799, DateTimeKind.Utc).AddTicks(9315),
                            Preview = "Blog created by DenisAdmin",
                            Title = "DenisAdmin Blog",
                            Type = "Post"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "TEST 2",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 7, 11, 52, 799, DateTimeKind.Utc).AddTicks(9317),
                            Preview = "Blog created by DenisGuest",
                            Title = "DenisGuest Blog",
                            Type = "Post"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Content = "TEST 3",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 6, 11, 52, 799, DateTimeKind.Utc).AddTicks(9319),
                            Title = "DenisPrime Blog",
                            Type = "Post"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Content = "TEST NEWS 1",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 6, 11, 52, 799, DateTimeKind.Utc).AddTicks(9320),
                            Title = "DenisAdmin News 1",
                            Type = "News"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Content = "TEST NEWS 2",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 5, 11, 52, 799, DateTimeKind.Utc).AddTicks(9321),
                            Title = "DenisAdmin News 3",
                            Type = "News"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Content = "TEST NEWS 3",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 4, 11, 52, 799, DateTimeKind.Utc).AddTicks(9322),
                            Title = "DenisAdmin News 3",
                            Type = "News"
                        });
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.BlogUserBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"BlogUserBookmark_Seq\"')");

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId", "BlogId")
                        .IsUnique();

                    b.ToTable("BlogUserBookmarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.BlogUserComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"BlogUserComment_Seq\"')");

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId", "BlogId")
                        .IsUnique();

                    b.ToTable("BlogUserComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 1,
                            CommentText = "Comment from DenisGuest",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 8, 11, 52, 799, DateTimeKind.Utc).AddTicks(9629),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 1,
                            CommentText = "Comment from DenisPrime",
                            CreatedDateUtc = new DateTime(2022, 10, 25, 5, 11, 52, 799, DateTimeKind.Utc).AddTicks(9631),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.BlogUserReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"BlogUserReview_Seq\"')");

                    b.Property<int>("BlogId")
                        .HasColumnType("integer");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId", "BlogId")
                        .IsUnique();

                    b.ToTable("BlogUserReviews");

                    b.HasCheckConstraint("CK_BlogUserReview_Grade", "\"Grade\" >= -1 AND \"Grade\" <= 1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 2,
                            Grade = (short)0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 3,
                            Grade = (short)1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 1,
                            Grade = (short)1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 3,
                            Grade = (short)1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            BlogId = 1,
                            Grade = (short)0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            BlogId = 2,
                            Grade = (short)-1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"Tags_Seq\"')");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Title = ".NET 6"
                        },
                        new
                        {
                            Id = 3,
                            Title = "PostgreSQL"
                        },
                        new
                        {
                            Id = 4,
                            Title = "SignalR"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Web-design"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Android"
                        },
                        new
                        {
                            Id = 7,
                            Title = "IT-companies"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Security"
                        });
                });

            modelBuilder.Entity("Resty.Data.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"Users_Seq\"')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Rating");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "deniskaminsky123@mail.ru",
                            FirstName = "Denis",
                            LastName = "Kaminsky",
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            Rating = 900,
                            Role = "Admin",
                            StartDateUtc = new DateTime(2022, 7, 17, 8, 11, 52, 799, DateTimeKind.Utc).AddTicks(8839),
                            Username = "DenisAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "deniskaminskyGuest@mail.ru",
                            FirstName = "Denis",
                            LastName = "KaminskyGuest",
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            Rating = 1,
                            Role = "GuestUser",
                            StartDateUtc = new DateTime(2022, 10, 15, 8, 11, 52, 799, DateTimeKind.Utc).AddTicks(8844),
                            Username = "DenisGuest"
                        },
                        new
                        {
                            Id = 3,
                            Email = "deniskaminskyPrime@mail.ru",
                            FirstName = "Denis",
                            LastName = "KaminskyPrime",
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            Rating = 3,
                            Role = "PrimeUser",
                            StartDateUtc = new DateTime(2022, 10, 20, 8, 11, 52, 799, DateTimeKind.Utc).AddTicks(8845),
                            Username = "DenisPrime"
                        });
                });

            modelBuilder.Entity("BlogTag", b =>
                {
                    b.HasOne("Resty.Data.Models.Blog.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resty.Data.Models.Blog.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.Blog", b =>
                {
                    b.HasOne("Resty.Data.Models.User.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.BlogUserBookmark", b =>
                {
                    b.HasOne("Resty.Data.Models.Blog.Blog", "Blog")
                        .WithMany("UserBookmarks")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resty.Data.Models.User.User", "User")
                        .WithMany("BlogBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.BlogUserComment", b =>
                {
                    b.HasOne("Resty.Data.Models.Blog.Blog", "Blog")
                        .WithMany("UserComments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resty.Data.Models.User.User", "User")
                        .WithMany("BlogComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.BlogUserReview", b =>
                {
                    b.HasOne("Resty.Data.Models.Blog.Blog", "Blog")
                        .WithMany("UserReviews")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Resty.Data.Models.User.User", "User")
                        .WithMany("BlogReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Resty.Data.Models.Blog.Blog", b =>
                {
                    b.Navigation("UserBookmarks");

                    b.Navigation("UserComments");

                    b.Navigation("UserReviews");
                });

            modelBuilder.Entity("Resty.Data.Models.User.User", b =>
                {
                    b.Navigation("BlogBookmarks");

                    b.Navigation("BlogComments");

                    b.Navigation("BlogReviews");

                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
